config/routes.rb
Rails.application.routes.draw do
  resources :zombies do
    resources :brains
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
    get '/sexto/cerebros', to: 'brains#index', as: 'brains'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brain.rb
class Brain < ApplicationRecord
    belongs_to :zombie
    validates :flavor, presence: true
    validates :iq, numericality: {only_integer: true, message: "Solo numeros enteros prro"}
end

app/models/zombie.rb
class Zombie < ApplicationRecord
    has_many :brains, dependent: :destroy
    validates :name, presence: true
    validates :age, numericality: {only_integer: true, message: "Solo numeros enteros prro"}
    validates :bio, length: { in: 1..100 , message: "Maximo 100 caracteres prro"}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, format: { :with => VALID_EMAIL_REGEX , message: "El formato del correo es invalido" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  before_action :set_brain, only: [:show, :edit, :update, :destroy]

  # GET /brains
  # GET /brains.json
  def index
    @brains = Brain.all
  end

  # GET /brains/1
  # GET /brains/1.json
  def show
  end

  # GET /brains/new
  def new
    @brain = Brain.new
  end

  # GET /brains/1/edit
  def edit
  end

  # POST /brains
  # POST /brains.json
  def create
      @zombie = Zombie.find(params[:zombie_id]);
      @brain = @zombie.brains.create(brain_params);

    respond_to do |format|
      if @brain.save
        format.html { redirect_to @brain, notice: 'Brain was successfully created.' }
        format.json { render :show, status: :created, location: @brain }
        format.js
      else
        format.html { render :new }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brains/1
  # PATCH/PUT /brains/1.json
  def update
    respond_to do |format|
      if @brain.update(brain_params)
        format.html { redirect_to @brain, notice: 'Brain was successfully updated.' }
        format.json { render :show, status: :ok, location: @brain }
      else
        format.html { render :edit }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /brains/1
  # DELETE /brains/1.json
  def destroy
    @brain.destroy
    respond_to do |format|
      format.html { redirect_to brains_url, notice: 'Brain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brain
      @brain = Brain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brain_params
      params.require(:brain).permit(:flavor, :iq, :fresh, :zombie_id)
    end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
    @rotten_zombies=Zombie.where(rotten:true)
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url, notice: 'Zombie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:name, :bio, :age, :email, :rotten)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brains_helper.rb
module BrainsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/brains/_brain.html.erb
<%= div_for brain do%>
<p>
<strong>
    Agregado:
    <%= time_ago_in_words(brain.created_at)%>
    </strong>
<br>
    <%= brain.flavor %>

</p>

<% end %>

app/views/brains/_form.html.erb
<%= form_for(brain) do |f| %>
  <% if brain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brain.errors.count, "error") %> prohibited this brain from being saved:</h2>

      <ul>
      <% brain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </div>

  <div class="field">
    <%= f.label :iq %>
    <%= f.number_field :iq %>
  </div>

  <div class="field">
    <%= f.label :fresh %>
    <%= f.check_box :fresh %>
  </div>

  <div class="field">
<%= f.collection_select :zombie_id, Zombie.order(:name), :id, :name, include_blank:true %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brains/create.js.erb

var new_brain=$("<%=escape_javascript(render(:partial=>@brain))%>").hide();
$('#brains').prepend(new_brain);
$('#brain_<%=@brain.id%>').fadeIn('slow');
$('#new_brain')[0].reset();

app/views/brains/edit.html.erb
<h1>Editing Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Show', @brain %> |
<%= link_to 'Back', brains_path %>

app/views/brains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brains</h1>

<table>
  <thead>
    <tr>
      <th>Flavor</th>
      <th>Iq</th>
      <th>Fresh</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brains.each do |brain| %>
      <tr>
        <td><%= brain.flavor %></td>
        <td><%= brain.iq %></td>
    
          <td>
          <% if brain.fresh %>
          <%= image_tag 'brains/fresh.png', class: 'brains_fresh' %>
              <% else %>
           <%= image_tag 'brains/no-fresh.png', class: 'brains_fresh' %>
              
          <% end %>
          
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/brains/new.html.erb
<h1>New Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Back', brains_path %>

app/views/brains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flavor:</strong>
  <%= @brain.flavor %>
</p>

<p>
  <strong>Iq:</strong>
  <%= @brain.iq %>
</p>

<p>
  <strong>Fresh:</strong>
  <%= @brain.fresh %>
</p>

<%= link_to 'Edit', edit_brain_path(@brain) %> |
<%= link_to 'Back', brains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/zombies/_form.html.erb
<%= form_for(zombie) do |f| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :rotten %>
    <%= f.check_box :rotten %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zombies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Age</th>
      <th>email</th>
      <th>rotten</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rotten_zombies.each do |zombie| %>
      <tr>
        <td><%= zombie.name %></td>
        <td><%= zombie.bio %></td>
        <td><%= zombie.age %></td>
        <td><%= zombie.email %></td>
    	  <td><%= zombie.rotten ? "yes" : "no"%></td>

        <td><%= link_to 'Show', zombie %></td>
        <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
        <td><%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zombie', new_zombie_path %>

app/views/zombies/new.html.erb
<h1>New Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zombie.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @zombie.bio %>
</p>

<p>
  <strong>Age:</strong>
  <%= @zombie.age %>
</p>
<p>
  <strong>Email:</strong>
  <%= @zombie.email %>
</p>
<p>
  <strong>Rotten:</strong>
  <%= @zombie.rotten %>
</p>

<div id="brains">
<%= render :partial => @zombie.brains.reverse %>
</div>

<%= form_for([@zombie, Brain.new], remote: true) do |f| %>
 
<div class="field">
<%= f.label :flavor %>
<%= f.text_field :flavor %>     
</div>

<div class="field">
<%= f.label :iq %>
<%= f.number_field :iq %>     
</div>

<div class="field">
<%= f.label :fresh %>
<%= f.check_box :fresh %>     
</div>

<div class="actions">
<%= f.submit "Add brain" %>

</div>
<% end %>


<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>